---
theme: jekyll-theme-architect
title: Progetto Bear
---
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
$().ready(function(){
    $.getJSON( "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json", function( data ) {
    console.log(data);
    $("#text").html(data[0]);
  });
});
</script>

<div id="text"></div>
